### ISSUE TITLE
Giveaway not working

### ISSUE THREAD

**Issue by TheFatalKiller** [fourjr/rainbot#1]
When a giveaway is trying to be created the following error comes up in Heroku logs:

2019-06-22T23:28:42.063813+00:00 app[worker.1]: Task exception was never retrieved
2019-06-22T23:28:42.063840+00:00 app[worker.1]: future: <Task finished coro=<Giveaways.__ainit__() done, defined at /app/cogs/giveaway.py:22> exception=KeyError('giveaway')>
2019-06-22T23:28:42.063841+00:00 app[worker.1]: Traceback (most recent call last):
2019-06-22T23:28:42.063844+00:00 app[worker.1]:   File "/app/cogs/giveaway.py", line 26, in __ainit__
2019-06-22T23:28:42.063846+00:00 app[worker.1]:     latest_giveaway = await self.get_latest_giveaway(guild_id=i.id)
2019-06-22T23:28:42.063848+00:00 app[worker.1]:   File "/app/cogs/giveaway.py", line 52, in get_latest_giveaway
2019-06-22T23:28:42.063849+00:00 app[worker.1]:     channel = await self.channel(ctx, guild_id=guild_id)
2019-06-22T23:28:42.063850+00:00 app[worker.1]:   File "/app/cogs/giveaway.py", line 34, in channel
2019-06-22T23:28:42.063851+00:00 app[worker.1]:     if guild_config['giveaway']['channel_id']:
2019-06-22T23:28:42.063854+00:00 app[worker.1]: KeyError: 'giveaway'

**Comment by fourjr** [comment]
Resolved
